# Problem Statement:
* You work in XYZ Corporation as a Data Analyst. Your corporation has told you to work with the 
  structure of the Data.

In [1]:
import numpy as np

# 1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [2]:

mat = np.matrix([[2,3,4],[5,6,7],[8,9,10]])
mat

matrix([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [3]:
mat.shape

(3, 3)

In [4]:
type(mat)

numpy.matrix

# 2. Create a numpy array having user input values and convert the integer type to the float type of the elements of the array. For instance:Original array
# [1, 2, 3, 4]
# Array converted to a float type:
# [ 1. 2. 3. 4.]

In [6]:
l= list(map(int,input('Enter list of values: ').split(',')))

Enter list of values: 2,3,4,5,6,7


In [7]:
arr = np.array(l,dtype = 'float')
arr

array([2., 3., 4., 5., 6., 7.])

# 3. Write a Numpy program to append values to the end of an array. For instance:
# Original array:
# [10, 20, 30]
# After append values to the end of the array:
# [10 20 30 40 50 60 70 80 90]

In [8]:
orig_arr = np.array([10,20,30])
orig_arr

array([10, 20, 30])

In [9]:
orig_arr = np.append(orig_arr,[40,50,60,70,80,90])
orig_arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# 4. Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2 = np.array([[10,20,30],[40,50,60]])
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
sumarray = arr1+arr2
sumarray

array([[11, 22, 33],
       [44, 55, 66]])

# 5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:

In [13]:
array1 = np.arange(10,100,10)
array1 = array1.reshape([3,3])
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# a. Extract the 1st row from the array.

In [14]:
array1[0,]

array([10, 20, 30])

# b. Extract the last element from the array.

In [15]:
array1[2,2]

90