In [1]:
#import numpy library

import numpy as np

In [2]:
#fill with  all zeros with 2x3 dimension
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
#Flatten convert 2d array into 1d array

arr = np.array([[1,2,3],[4,5,6]])
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [4]:
#convert 1D np arrray into 2d np array

In [5]:
arr1 = np.array([1,2,3,4,5,6])
arr1.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#to sort array
arr = np.array([[1,2,3,4,5,6]])
arr.sort()
arr

array([[1, 2, 3, 4, 5, 6]])